# Generated by Django 2.1.7 on 2019-06-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='howdidyouhear',
            field=models.CharField(blank=True, choices=[('FRIENDS', 'FRIENDS'), ('FACEBOOK', 'FACEBOOK'), ('NEWS', 'NEWS'), ('RADIO', 'RADIO')], default='FACEBOOK', help_text='How did you hear about us?', max_length=20, verbose_name='How did you heard about us?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='progoption',
            field=models.CharField(blank=True, choices=[('CASA', 'CASA'), ('GRADE SCHOOL', 'GRADE SCHOOL'), ('HOMESTUDY', 'HOMESTUDY'), ('HIGH SCHOOL', 'HIGH SCHOOL'), ('SPED', 'SPED')], default='CASA', help_text='Please select Program', max_length=20, verbose_name='Program Option'),
        ),
    ]
