# Generated by Django 2.1.7 on 2019-06-02 10:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('lgmssis', '0002_auto_20190602_1808'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('streetname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Name')),
                ('cityname', models.CharField(blank=True, max_length=255, null=True, verbose_name='City Name')),
                ('zip', models.IntegerField(blank=True, null=True, verbose_name='Zip Code')),
                ('mobilenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='MOBILE FORMAT : +639178888888', max_length=128, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('progoption', models.CharField(blank=True, choices=[('SPED', 'SPED'), ('CASA', 'CASA'), ('GRADE SCHOOL', 'GRADE SCHOOL'), ('HOMESTUDY', 'HOMESTUDY'), ('HIGH SCHOOL', 'HIGH SCHOOL')], default='CASA', help_text='Please select Program', max_length=20)),
                ('howdidyouhear', models.CharField(blank=True, choices=[('SPED', 'SPED'), ('CASA', 'CASA'), ('GRADE SCHOOL', 'GRADE SCHOOL'), ('HOMESTUDY', 'HOMESTUDY'), ('HIGH SCHOOL', 'HIGH SCHOOL')], default='FACEBOOK', help_text='How did you hear about us?', max_length=20)),
                ('country_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmssis.CountryOption')),
            ],
        ),
    ]
