# Generated by Django 2.1.7 on 2019-06-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='howdidyouhear',
            field=models.CharField(blank=True, choices=[('NEWS', 'NEWS'), ('FACEBOOK', 'FACEBOOK'), ('FRIENDS', 'FRIENDS'), ('RADIO', 'RADIO')], default='FACEBOOK', help_text='How did you hear about us?', max_length=20, verbose_name='How did you heard about us?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='progoption',
            field=models.CharField(blank=True, choices=[('SPED', 'SPED'), ('HIGH SCHOOL', 'HIGH SCHOOL'), ('HOMESTUDY', 'HOMESTUDY'), ('CASA', 'CASA'), ('GRADE SCHOOL', 'GRADE SCHOOL')], default='CASA', help_text='Please select Program', max_length=20, verbose_name='Program Option'),
        ),
    ]
