# Generated by Django 2.1.7 on 2019-06-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190608_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentsprofile',
            name='country_of_birth_parents',
        ),
        migrations.RemoveField(
            model_name='parentsprofile',
            name='user_parents',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='country_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user_student',
        ),
        migrations.RemoveField(
            model_name='teachersprofile',
            name='user_teachers',
        ),
        migrations.AlterField(
            model_name='application',
            name='howdidyouhear',
            field=models.CharField(blank=True, choices=[('NEWS', 'NEWS'), ('FACEBOOK', 'FACEBOOK'), ('RADIO', 'RADIO'), ('FRIENDS', 'FRIENDS')], default='FACEBOOK', help_text='How did you hear about us?', max_length=20, verbose_name='How did you heard about us?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='progoption',
            field=models.CharField(blank=True, choices=[('GRADE SCHOOL', 'GRADE SCHOOL'), ('SPED', 'SPED'), ('HOMESTUDY', 'HOMESTUDY'), ('HIGH SCHOOL', 'HIGH SCHOOL'), ('CASA', 'CASA')], default='CASA', help_text='Please select Program', max_length=20, verbose_name='Program Option'),
        ),
        migrations.DeleteModel(
            name='ParentsProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TeachersProfile',
        ),
    ]
