# Generated by Django 2.1.7 on 2019-05-21 02:25

from django.db import migrations, models
import django.db.models.deletion
import lgmssis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, verbose_name='First Name')),
                ('lname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('streetname', models.CharField(max_length=255, verbose_name='Street Name')),
                ('cityname', models.CharField(max_length=255, verbose_name='City Name')),
                ('zip', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CountryOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='country_of_birth',
            field=models.ForeignKey(blank=True, default=lgmssis.models.get_default_country, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmssis.CountryOption'),
        ),
    ]
