# Generated by Django 2.1.7 on 2019-05-21 03:35

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('lgmssis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cityname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City Name'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='country_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmssis.CountryOption'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='fname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='lname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='mobilenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='MOBILE FORMAT : +639178888888', max_length=128, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='streetname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Name'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='zip',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip Code'),
        ),
    ]
