# Generated by Django 2.1.7 on 2019-05-21 02:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('lgmssis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='mobilenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='MOBILE FORMAT : +639178888888', max_length=128, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='zip',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
