# Generated by Django 2.1.7 on 2019-05-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgmssis', '0002_auto_20190521_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='zip',
            field=models.IntegerField(blank=True, null=True, verbose_name='Zip Code'),
        ),
    ]
