# Generated by Django 2.1.7 on 2019-05-21 06:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('lgmssis', '0002_auto_20190521_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complete Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mobilenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='MOBILE FORMAT : +639178888888', max_length=128, null=True, verbose_name='Mobile Number')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place or City')),
                ('programme', models.CharField(blank=True, max_length=255, null=True, verbose_name='Course or Programme')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='graddate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='howdidyouhear',
            field=models.CharField(blank=True, choices=[('GRADE SCHOOL', 'GRADE SCHOOL'), ('HIGH SCHOOL', 'HIGH SCHOOL'), ('CASA', 'CASA'), ('HOMESTUDY', 'HOMESTUDY'), ('SPED', 'SPED')], default='FACEBOOK', help_text='How did you hear about us?', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='progoption',
            field=models.CharField(blank=True, choices=[('GRADE SCHOOL', 'GRADE SCHOOL'), ('HIGH SCHOOL', 'HIGH SCHOOL'), ('CASA', 'CASA'), ('HOMESTUDY', 'HOMESTUDY'), ('SPED', 'SPED')], default='CASA', help_text='Please select Program', max_length=20),
        ),
    ]
