# Generated by Django 2.1.7 on 2019-05-21 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgmssis', '0003_auto_20190521_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='country_of_birth',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
