# Generated by Django 2.1.7 on 2019-06-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgmssis', '0003_auto_20190609_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='faculty_users',
            new_name='fuser',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='howdidyouhear',
            field=models.CharField(blank=True, choices=[('HOMESTUDY', 'HOMESTUDY'), ('SPED', 'SPED'), ('GRADE SCHOOL', 'GRADE SCHOOL'), ('CASA', 'CASA'), ('HIGH SCHOOL', 'HIGH SCHOOL')], default='FACEBOOK', help_text='How did you hear about us?', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='progoption',
            field=models.CharField(blank=True, choices=[('HOMESTUDY', 'HOMESTUDY'), ('SPED', 'SPED'), ('GRADE SCHOOL', 'GRADE SCHOOL'), ('CASA', 'CASA'), ('HIGH SCHOOL', 'HIGH SCHOOL')], default='CASA', help_text='Please select Program', max_length=20),
        ),
    ]
