# Generated by Django 2.1.7 on 2019-06-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgmssis', '0007_auto_20190610_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='howdidyouhear',
            field=models.CharField(blank=True, choices=[('CASA', 'CASA'), ('GRADE SCHOOL', 'GRADE SCHOOL'), ('SPED', 'SPED'), ('HIGH SCHOOL', 'HIGH SCHOOL'), ('HOMESTUDY', 'HOMESTUDY')], default='FACEBOOK', help_text='How did you hear about us?', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='progoption',
            field=models.CharField(blank=True, choices=[('CASA', 'CASA'), ('GRADE SCHOOL', 'GRADE SCHOOL'), ('SPED', 'SPED'), ('HIGH SCHOOL', 'HIGH SCHOOL'), ('HOMESTUDY', 'HOMESTUDY')], default='CASA', help_text='Please select Program', max_length=20),
        ),
    ]
