# Generated by Django 2.1.7 on 2019-06-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgmssis', '0011_auto_20190611_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='howdidyouhear',
            field=models.CharField(blank=True, choices=[('CASA', 'CASA'), ('HOMESTUDY', 'HOMESTUDY'), ('HIGH SCHOOL', 'HIGH SCHOOL'), ('GRADE SCHOOL', 'GRADE SCHOOL'), ('SPED', 'SPED')], default='FACEBOOK', help_text='How did you hear about us?', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='progoption',
            field=models.CharField(blank=True, choices=[('CASA', 'CASA'), ('HOMESTUDY', 'HOMESTUDY'), ('HIGH SCHOOL', 'HIGH SCHOOL'), ('GRADE SCHOOL', 'GRADE SCHOOL'), ('SPED', 'SPED')], default='CASA', help_text='Please select Program', max_length=20),
        ),
    ]
