# Generated by Django 2.1.7 on 2019-06-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgmssis', '0012_auto_20190611_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='howdidyouhear',
            field=models.CharField(blank=True, choices=[('HOMESTUDY', 'HOMESTUDY'), ('HIGH SCHOOL', 'HIGH SCHOOL'), ('CASA', 'CASA'), ('GRADE SCHOOL', 'GRADE SCHOOL'), ('SPED', 'SPED')], default='FACEBOOK', help_text='How did you hear about us?', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='progoption',
            field=models.CharField(blank=True, choices=[('HOMESTUDY', 'HOMESTUDY'), ('HIGH SCHOOL', 'HIGH SCHOOL'), ('CASA', 'CASA'), ('GRADE SCHOOL', 'GRADE SCHOOL'), ('SPED', 'SPED')], default='CASA', help_text='Please select Program', max_length=20),
        ),
    ]
