<<<<<<< HEAD
# Generated by Django 2.1.7 on 2019-06-18 08:52
=======
# Generated by Django 2.1.7 on 2019-06-18 08:12
>>>>>>> 35070d9d4956975ca6dca47096f42df732eb9730

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
        ('lgmssis', '0003_auto_20190618_1652'),
=======
        ('lgmssis', '0014_auto_20190618_1612'),
>>>>>>> 35070d9d4956975ca6dca47096f42df732eb9730
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', ckeditor.fields.RichTextField(blank=True)),
                ('follow_up_notes', models.CharField(blank=True, max_length=2024)),
                ('file', models.FileField(blank=True, null=True, upload_to='student_meetings')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='StudentMeetingCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentmeeting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmscounsel.StudentMeetingCategory'),
        ),
        migrations.AddField(
            model_name='studentmeeting',
            name='follow_up_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmscounsel.FollowUpAction'),
        ),
        migrations.AddField(
            model_name='studentmeeting',
            name='reported_by',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentmeeting',
            name='students',
            field=models.ManyToManyField(to='lgmssis.Student'),
        ),
    ]
