"""
Django settings for online_lgms project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mq-%3au71tv*w-((*ie%x^b-y3r@*-br$x6_8f)2)+!aoe-4um'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
          'www.learninggardenmontessori.ph',
          '127.0.0.1',
		  '192.168.0.103',
		  '122.3.47.190',
]


# Application definition

INSTALLED_APPS = [

    'jet.dashboard',
    'jet',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'phonenumber_field',
    'crispy_forms',
    'users.apps.UsersConfig',
    'lgmssis.apps.LgmssisConfig',
    'lgmsschedule.apps.LgmsscheduleConfig',
    # 'lgmstest.apps.LgmstestConfig',
     'lgmsgrades.apps.LgmsgradesConfig',
    # 'lgmsattendance.apps.LgmsattendanceConfig',
    # 'lgmsadmin.apps.LgmsadminConfig',
    'ajax_select',
    'lgmsdiscipline.apps.LgmsdisciplineConfig',
    'rangefilter',
    'lgmsadmission.apps.LgmsadmissionConfig',
    'lgmscounsel',
    'ckeditor',
    'lgmsbenchmarkgrade',
    'lgmsbenchmarks',
    'lgmsadmin',
    'lgmsexam',
    'custom_field',
    'django_thumbs',


]

CRISPY_TEMPLATE_PACK = 'uni_form'

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
]

# CSRF_COOKIE_SECURE = True
# X_FRAME_OPTIONS = 'DENY'
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SESSION_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True

ROOT_URLCONF = 'online_lgms.urls'

#this is from the django-jet
# from django.conf import global_settings
#
# TEMPLATE_CONTEXT_PROCESSORS = global_settings.TEMPLATE_CONTEXT_PROCESSORS + (
#     'django.core.context_processors.request',
# )

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'online_lgms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),

        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'lgmsschool',
        'USER': 'testroot',
        'PASSWORD': 'testroot',
		'OPTIONS': {
    	'sql_mode': 'STRICT_TRANS_TABLES',},
		#'https://console.cloud.google.com/sql/instances'
        #'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        #'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Hong_Kong'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#STATIC_ROOT = '/home/lgms/lgms/online_lgms/staticfiles'
#STATIC_ROOT = '/Users/wackygalang/Projects/clones/online_lgms/staticfiles'
#
STATIC_ROOT = 'wackyproject/project/clones/online_lgms/staticfiles'
STATIC_URL = '/static/'


#uploaded files
MEDIA_ROOT = os.path.join(BASE_DIR, 'users/media')
MEDIA_URL = '/media/'

ADMISSIONS_DEFAULT_COUNTRY = "Philippines"


#this has been added as a test because I am trying to implement a separate Group
#AUTH_USER_MODEL = 'users.User'


#test of settings only - should be home but changed to home
LOGIN_REDIRECT_URL = 'profile'

LOGIN_URL = 'login'



#for email 
#EMAIL_BACKEND = ‘django.core.mail.backends.smtp.EmailBackend’
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'learninggardenmontessoridrive@gmail.com'
EMAIL_HOST_PASSWORD = 'Foundation2000'


AJAX_LOOKUP_CHANNELS = {
    # the simplest case, pass a DICT with the model and field to search against :

    'student' : ('lgmssis.lookups', 'StudentLookup'),
    'discstudent' : ('lgmsdiscipline.lookups', 'StudentWithDisciplineLookup'),
    'all_student' : ('lgmssis.lookups', 'AllStudentLookup'),
    'course': {'model':'lgmsschedule.course', 'search_field':'full_name'},
    'day': ('lgmsschedule.lookups','DayLookup'),
}



CRISPY_TEMPLATE_PACK = 'bootstrap4'


GOOGLE_RECAPTCHA_SECRET_KEY = '6Ldj-6gUAAAAAN2RJCuVaanwM7Z_J2x_IWHWtRNW'


CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"

CKEDITOR_UPLOAD_PATH = "uploads/"