# Generated by Django 2.1.7 on 2019-06-11 05:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('major_offense', models.BooleanField(help_text='This can be filtered by on Grade Analytics and other reports.')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineActionInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(help_text='If comment is "Case note" these infractions will not be counted as a discipline issue in reports', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('comments', models.TextField(blank=True)),
                ('private_note', models.TextField(blank=True)),
                ('action', models.ManyToManyField(through='lgmsdiscipline.DisciplineActionInstance', to='lgmsdiscipline.DisciplineAction')),
                ('infraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmsdiscipline.Infraction')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
