# Generated by Django 2.1.7 on 2019-06-11 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lgmsschedule', '0001_initial'),
        ('lgmssis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingperiod',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgmssis.SchoolYear'),
        ),
        migrations.AddField(
            model_name='daysoff',
            name='marking_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgmsschedule.MarkingPeriod'),
        ),
        migrations.AddField(
            model_name='coursemeet',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgmsschedule.Course'),
        ),
        migrations.AddField(
            model_name='coursemeet',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmsschedule.Location'),
        ),
        migrations.AddField(
            model_name='coursemeet',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgmsschedule.Period'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgmsschedule.Course'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='exclude_days',
            field=models.ManyToManyField(blank=True, help_text='Student does not need to attend on this day. Note courses already specify meeting days, this field is for students who have a special reason to be away', to='lgmsschedule.Day'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmssis.GradeLevel'),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollments',
            field=models.ManyToManyField(blank=True, through='lgmsschedule.CourseEnrollment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmssis.GradeLevel'),
        ),
        migrations.AddField(
            model_name='course',
            name='marking_period',
            field=models.ManyToManyField(blank=True, to='lgmsschedule.MarkingPeriod'),
        ),
        migrations.AddField(
            model_name='course',
            name='periods',
            field=models.ManyToManyField(blank=True, through='lgmsschedule.CourseMeet', to='lgmsschedule.Period'),
        ),
        migrations.AddField(
            model_name='course',
            name='secondary_teachers',
            field=models.ManyToManyField(blank=True, related_name='secondary_teachers', to='lgmssis.Faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ateacher', to='lgmssis.Faculty'),
        ),
        migrations.AddField(
            model_name='awardstudent',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgmsschedule.Award'),
        ),
        migrations.AddField(
            model_name='awardstudent',
            name='marking_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmsschedule.MarkingPeriod'),
        ),
        migrations.AddField(
            model_name='awardstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lgmssis.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('course', 'user', 'role')},
        ),
    ]
