# Generated by Django 2.1.7 on 2019-06-10 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgmsschedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markingperiod',
            old_name='ame',
            new_name='name',
        ),
    ]
