# Generated by Django 2.1.7 on 2019-06-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('override_final', models.BooleanField(blank=True, help_text='Override final grade for marking period instead of calculating it.', null=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('letter_grade', models.CharField(blank=True, choices=[('E', 'Excellent'), ('VG', 'Very Good'), ('G', 'Good'), ('S', 'Satisfactory'), ('F', 'Fair'), ('NI', 'Needs Improvement / Passed'), ('U', 'Unsatisfactory / Failed')], help_text='Will override grade.', max_length=2, null=True)),
            ],
            options={
                'permissions': (('change_own_grade', 'Change grades for own class'), ('change_own_final_grade', 'Change final YTD grades for own class')),
            },
        ),
        migrations.CreateModel(
            name='GradeComment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
