# Generated by Django 2.1.7 on 2019-06-11 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lgmsschedule', '0001_initial'),
        ('lgmsgrades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmsschedule.Course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='marking_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmsschedule.MarkingPeriod'),
        ),
    ]
