# Generated by Django 2.1.7 on 2019-06-10 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lgmssis', '0009_auto_20190610_1430'),
        ('lgmsschedule', '0002_auto_20190610_1157'),
        ('lgmsgrades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeComment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'permissions': (('change_own_grade', 'Change grades for own class'), ('change_own_final_grade', 'Change final YTD grades for own class'))},
        ),
        migrations.AddField(
            model_name='grade',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmsschedule.Course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='letter_grade',
            field=models.CharField(blank=True, choices=[('E', 'Excellent'), ('VG', 'Very Good'), ('G', 'Good'), ('S', 'Satisfactory'), ('F', 'Fair'), ('NI', 'Needs Improvement / Passed'), ('U', 'Unsatisfactory / Failed')], help_text='Will override grade.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='marking_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lgmsschedule.MarkingPeriod'),
        ),
        migrations.AddField(
            model_name='grade',
            name='override_final',
            field=models.BooleanField(blank=True, help_text='Override final grade for marking period instead of calculating it.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'course', 'marking_period')},
        ),
    ]
